%{ 
script to help evaluate the compactness performance as the number of
clusters increase

%}

%% init values to test on

clusters_to_evaluate = 2:15;
number_of_rand_initalization = 20;
isPlot = 1;
isDisplay = 1;
numReplicates = 5;

%% Standard Kmeans

evaluate_clusters_of_standard(clusters_to_evaluate, ...
                             number_of_rand_initalization, ...
                             toysylvania_information, ...
                             newflormedium_information, ...
                             isPlot, ...
                             isDisplay, ...
                             numReplicates);


%% Soft Start

evaluate_clusters_of_soft(clusters_to_evaluate, ...
                             number_of_rand_initalization, ...
                             toysylvania_information, ...
                             newflormedium_information, ...
                             isPlot, ...
                             isDisplay, ...
                             numReplicates);

%% Soft Start w/ L1

evaluate_clusters_of_soft_L1(clusters_to_evaluate, ...
                             number_of_rand_initalization, ...
                             toysylvania_information, ...
                             newflormedium_information, ...
                             isPlot, ...
                             isDisplay, ...
                             numReplicates);

%% Soft Start w/ L2

evaluate_clusters_of_soft_L2(clusters_to_evaluate, ...
                             number_of_rand_initalization, ...
                             toysylvania_information, ...
                             newflormedium_information, ...
                             isPlot, ...
                             isDisplay, ...
                             numReplicates);

                         
%% BKMG

evaluate_clusters_of_soft_L2(clusters_to_evaluate, ...
                             number_of_rand_initalization, ...
                             toysylvania_information, ...
                             newflormedium_information, ...
                             isPlot, ...
                             isDisplay, ...
                             numReplicates);
                         
                         
                         
                         
                         
                         
                         
                         
                         
                         