%{
script to evaluate standard kmeans with replacement

%}


%% run standard kmeans with 10 replacements and L1 minimization

%%% toysylvania
clusters = 4; numReplicates = 10; isPlot = 0; isDetails = 0; 
[toysylvania_people_in_clusters, toysylvania_clusters_idx, toysylvania_cluster_centers] = ...
    standard_kmeans_alg(toysylvania_information,clusters,numReplicates,isPlot,isDetails);                       
[cluster_norm_standard_kmeans_toysylvania, ...
    L1_max_standard_kmeans_toysylvania, ...
    L2_max_standard_kmeans_toysylvania] = evaluate_compactness(...
                                          toysylvania_people_in_clusters, ...
                                          toysylvania_cluster_centers);


%%% newflormedium
clusters = 5; numReplicates = 10; isPlot = 0; isDetails = 0; 
[newflormedium_people_in_clusters, newflormedium_clusters_idx, newflormedium_cluster_centers] = ...
    standard_kmeans_alg(newflormedium_information,clusters,numReplicates,isPlot,isDetails);                          
[cluster_norm_standard_kmeans_newflormedium, ...
    L1_max_standard_kmeans_newflormedium, ...
    L2_max_standard_kmeans_newflormedium] = evaluate_compactness(...
                                            newflormedium_people_in_clusters, ...
                                            newflormedium_cluster_centers);


%%% smallerado
clusters = 7; numReplicates = 10; isPlot = 0; isDetails = 0; 
[smallerado_people_in_clusters, smallerado_clusters_idx, smallerado_cluster_centers] = ...
    standard_kmeans_alg(smallerado_information,clusters,numReplicates,isPlot,isDetails);                          
[cluster_norm_standard_kmeans_smallerado, ...
    L1_max_standard_kmeans_smallerado, ...
    L2_max_standard_kmeans_smallerado] = evaluate_compactness(...
                                         smallerado_people_in_clusters, ...
                                         smallerado_cluster_centers);

%%% largerado
clusters = 7; numReplicates = 10; isPlot = 1; isDetails = 0;
[largerado_people_in_clusters, largerado_clusters_idx, largerado_cluster_centers] = ...
    standard_kmeans_alg(largerado_information,clusters,numReplicates,isPlot,isDetails);                         
[cluster_norm_standard_kmeans_largerado, ...
    L1_max_standard_kmeans_largerado, ...
    L2_max_standard_kmeans_largerado] = evaluate_compactness(...
                                        largerado_people_in_clusters, ...
                                        largerado_cluster_centers);
                                    
                                    
                                    