%{
script to help evaluate the soft start with the compact constrant of L1

%}

%% Increase the compactness by minimizing the L1 distance intracluster

%%% toysylvania
clusters = 4; numReplicates = 10; isPlot = 1; isDetails = 0;
[toysylvania_people_in_clusters_soft_L1, toysylvania_clusters_idx_soft_L1, toysylvania_cluster_centers_soft_L1] = ...
    soft_start_L1_min_kmeans(toysylvania_information,clusters,numReplicates,isPlot,isDetails);                       
[cluster_norm_soft_start_L1_min_kmeans_toysylvania, ...
    L1_max_soft_start_L1_min_kmeans_toysylvania, ...
    L2_max_soft_start_L1_min_kmeans_toysylvania] = evaluate_compactness(...
                                            toysylvania_people_in_clusters_soft_L1, ...
                                            toysylvania_cluster_centers_soft_L1);
                                        

%%% newflormedium
clusters = 5; numReplicates = 10; isPlot = 1; isDetails = 0;
[newflormedium_people_in_clusters_soft_L1, newflormedium_clusters_idx_soft_L1, newflormedium_cluster_centers_soft_L1] = ...
    soft_start_L1_min_kmeans(newflormedium_information,clusters,numReplicates,isPlot,isDetails);                       
[cluster_norm_soft_start_L1_min_kmeans_newflormedium, ...
    L1_max_soft_start_L1_min_kmeans_newflormedium, ...
    L2_max_soft_start_L1_min_kmeans_newflormedium] = evaluate_compactness(...
                                            newflormedium_people_in_clusters_soft_L1, ...
                                            newflormedium_cluster_centers_soft_L1);
                                        
%%% smallerado
clusters = 7; numReplicates = 10; isPlot = 1; isDetails = 0;
[smallerado_people_in_clusters_soft_L1, smallerado_clusters_idx_soft_L1, smallerado_cluster_centers_soft_L1] = ...
    soft_start_L1_min_kmeans(smallerado_information,clusters,numReplicates,isPlot,isDetails);                       
[cluster_norm_soft_start_L1_min_kmeans_smallerado, ...
    L1_max_soft_start_L1_min_kmeans_smallerado, ...
    L2_max_soft_start_L1_min_kmeans_smallerado] = evaluate_compactness(...
                                            smallerado_people_in_clusters_soft_L1, ...
                                            smallerado_cluster_centers_soft_L1);

%%% largerado
clusters = 7; numReplicates = 10; isPlot = 0; isDetails = 0;
[largerado_people_in_clusters_soft_L1, largerado_clusters_idx_soft_L1, largerado_cluster_centers_soft_L1] = ...
    soft_start_L1_min_kmeans(largerado_information,clusters,numReplicates,isPlot,isDetails);                       
[cluster_norm_soft_start_L1_min_kmeans_largerado, ...
    L1_max_soft_start_L1_min_kmeans_largerado, ...
    L2_max_soft_start_L1_min_kmeans_largerado] = evaluate_compactness(...
                                            largerado_people_in_clusters_soft_L1, ...
                                            largerado_cluster_centers_soft_L1);

